from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

@dataclass
class Evidence:
    """
    Standardized data contract representing a single piece of evidence
    generated by a specific EvidenceProvider.
    """
    source: str                    # Name of the provider (e.g., "whisper_reasoning", "aasist", "heuristics", "rag_match", "verification")
    score: float                   # Risk contribution (0.0 to 1.0)
    confidence: float              # Reliable evaluation metrics (0.0 to 1.0)
    weight: float = 1.0            # Relative importance weight of this provider in fusion
    details: Dict[str, Any] = field(default_factory=dict) # Raw outputs from the provider (e.g. hits, category)
    explanation: str = ""          # Human-readable reasoning explaining this provider's score

class EvidenceProvider(ABC):
    """
    Abstract interface implemented by all evidence extraction components.
    """
    
    @property
    @abstractmethod
    def name(self) -> str:
        """
        Returns the unique identifier name of this provider.
        """
        pass

    @abstractmethod
    async def evaluate(self, context: Dict[str, Any]) -> Evidence:
        """
        Evaluates the session context to extract evidence.
        """
        pass
