import asyncio
import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.services.report_generator import ReportGenerator

async def main():
    print("==================================================")
    print("Testing Plan B ReportGenerator Service & Groq LLM")
    print("==================================================")

    dummy_data = {
        "transcript": "Hello, I am calling from SBI card division. Your account is blocked due to incomplete KYC. Share OTP immediately or face legal action.",
        "risk_score": 0.95,
        "label": "SCAM",
        "scam_category": "Bank Impersonation Scams",
        "overall_confidence": 0.85,
        "explanation": "The caller claims to be an SBI official and threatens account block while demanding an OTP.",
        "caller_number": "+91 9876543210",
        "duration_s": 22.5,
        "advisories": [
            {
                "title": "RBI Warning on KYC Update Phishing",
                "source": "RBI Advisory",
                "description": "Banks never ask for OTP or password over phone.",
                "url": "https://rbi.org.in"
            }
        ],
        "reasoning_trace": [
            "[Transcript] High threat detected.",
            "[Evidence Fusion] Threat level evaluated at 95%."
        ]
    }

    result = await ReportGenerator.generate_report(dummy_data)

    print("\n[Executive Summary Generated by Groq]:")
    print(result["executive_summary"])

    print(f"\n[SHA-256 Audit Hash]: {result['sha256_hash']}")

    assert len(result["executive_summary"]) > 20, "Executive summary should not be empty!"
    assert len(result["sha256_hash"]) == 64, "SHA-256 hash must be 64 hex characters!"
    assert "INCIDENT AUDIT REPORT" in result["report_text"], "Report text must contain header!"

    print("\n==================================================")
    print("ALL PLAN B REPORT GENERATOR TESTS PASSED!")
    print("==================================================")

if __name__ == "__main__":
    asyncio.run(main())
